### ISSUE TITLE
No Cards

### ISSUE THREAD

**Issue by gaochongGithub** [RACE-Game/race#6]
![7DB29E79-4747-41cb-91D3-D5BE4074B395](https://github.com/RACE-Game/race/assets/38418203/a096bea2-ba33-42d5-92bf-33f8e1f3aaca)
![BA9E9AC6-8ADF-43ce-BC6F-2B6E0C7C8E8E](https://github.com/RACE-Game/race/assets/38418203/901b708a-4c9c-41e5-be6c-757a4cfec146)

I rewritten it with the engine, but I can't get the card value, the code is not executing after appclient_get_revealed, please help me.

**Comment by DogLooksGood** [comment]
You are on the main branch?

**Comment by gaochongGithub** [comment]
It has been solved thank you
